### ISSUE TITLE
AttributeError: module 'xacro' has no attribute 'process'

### ISSUE THREAD

**Issue by joaomoura24** [cmower/optas#78] opened 2023-02-17 11:20 UTC
When running the simple_joint_space_planner.py example in the master branch i get the following error related with the xacro functionality:

`Traceback (most recent call last):
  File "example/simple_joint_space_planner.py", line 138, in <module>
    main()
  File "example/simple_joint_space_planner.py", line 102, in main
    kuka = KukaLBR()
  File "/home/joao/Documents/Projects/test/optas/example/pybullet_api.py", line 168, in __init__
    urdf_string = xacro.process(xacro_filename)
AttributeError: module 'xacro' has no attribute 'process'
`

**Comment by cmower** [comment] 2023-02-17 12:04
Ahh, I can reproduce this error. This is happening because you have ROS1 sourced and the `xacro` module is being imported from the ROS1 distribution packages - and I believe this is an older version of `xacro`. I have the updated version installed so works for me, but when I source ROS1, the old package is imported and I get the same failure. 

I will look into how to resolve this issue in general.

**Comment by joaomoura24** [comment] 2023-02-17 12:08
Ok. Ideally this wouldn't depend on having ROS installed at all even.
Using some package for xacro that is available through pip.

**Comment by cmower** [comment] 2023-02-17 12:09
This isn't depending on ROS, but because you have ROS1 the different version is being imported.

**Comment by cmower** [comment] 2023-02-17 12:10
I've found a solution, and implementing now.

**Comment by cmower** [comment] 2023-02-17 12:52
Ok, this is a little more difficult than I thought. So, xacro can run in a ROS agnostic environment. However, "[this implies that you cannot use ROS-specific features in xacro](https://github.com/ros/xacro/issues/197)". We can look into modifying the `med7` xacro file, but we should make a "Known issues" section in the README/documentation.

**Comment by cmower** [comment] 2023-02-17 13:16
011f77ea30f3b70ef88a10ce34aaed44b63e6d2c is a small example of the things that need to be removed from the xacro file so it can be loaded in a ROS agnostic environment.

**Comment by cmower** [comment] 2023-02-17 13:17
Closing, this will be resolved when #79 is merged.

**Closed by cmower** 2023-02-17 13:17 UTC
Labels: invalid
